name:                hs-ciobanu
version:             0.1.0.0
github:              ssipos90/hs-ciobanu
license:             BSD3
author:              Sebastian Sipos
maintainer:          sebastiansipos90@gmail.com
copyright:           MIT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ssipos90/hs-ciobanu#readme>

dependencies:
- aeson >= 1.4.7
- AesonBson >= 0.4.0
- base >= 4.11 && < 10
- bson >= 0.4.0.1
- bytestring >= 0.10.8.2 && < 0.11
- rio >= 0.1.12.0
- microlens >= 0.4.11.2 && < 0.5
- microlens-mtl >= 0.2.0 && < 0.3
- microlens-th >= 0.4.2 && < 0.5
- mongoDB >= 2.7.0
- scotty >= 0.11.6
- time >= 1.9.3
- text >= 1.2.3.4
- vector >= 0.12.1.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings

executables:
  hs-ciobanu-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - hs-ciobanu
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  hs-ciobanu-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hs-ciobanu
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
